eKnihy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# django.contrib.auth.urls obsahuje defaultní nastavení pro login a logout, takže se nemusí uvádět ve views.py
urlpatterns = [
    path('admin/', admin.site.urls),
    path('clanky/', include('databaze_eknih.urls')),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
    path('', include('knihy.urls')),
]
# pro čtení media souborů
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

knihy/urls.py
from django.urls import path
from .views import BooksView, AddBookView, BookDetailView, UpdateBookDetail, SearchView, AddAuthorView, AuthorDetailView, AllBooksView, AllAuthorsView, GenreDetailView
from .views import AuthorsByCharView, BooksByCharView ,DeleteBookDetailView, AuthorAutocompleteView, DownloadEpubView, AddPublisherView, PublisherAutocompleteView, PublisherDetailView

urlpatterns = [
    path("", BooksView.as_view(), name="home"),
    path("pridat-knihu/", AddBookView.as_view(), name="pridat-knihu"),
    path("detail-knihy/<slug:slug>", BookDetailView.as_view(), name="detail-knihy"),
    path("upravit-knihu/<slug:slug>", UpdateBookDetail.as_view(), name="upravit-knihu"),
    path("smazat-knihu/<slug:slug>", DeleteBookDetailView.as_view(), name="smazat-knihu"),
    path("vysledky-hledani", SearchView.as_view(), name="vysledky-hledani"),
    path("pridat-autora", AddAuthorView.as_view(), name="pridat-autora"),
    path("pridat-nakladatelstvi", AddPublisherView.as_view(), name="pridat-nakladatelstvi"),
    path("detail-autora/<slug:slug>", AuthorDetailView.as_view(), name="detail-autora"),
    path("detail-nakladatelstvi/<slug:slug>", PublisherDetailView.as_view(), name="detail-nakladatelstvi"),
    path("vsechny-knihy/", AllBooksView.as_view(), name="vsechny-knihy"),
    path("vsichni-autori/", AllAuthorsView.as_view(), name="vsichni-autori"),
    path("autori-abecedne-<str:char>", AuthorsByCharView.as_view(), name="vsichni-autori-abecedne"),
    path("knihy-abecedne-<str:char>", BooksByCharView.as_view(), name="vsechny-knihy-abecedne"),
    path("zanr-<slug:slug>", GenreDetailView.as_view(), name="zanr"),
    path("author-autocomplete/", AuthorAutocompleteView.as_view(), name="author-autocomplete"),
    path("publisher-autocomplete/", PublisherAutocompleteView.as_view(), name="publisher-autocomplete"),
    path("stahnout-knihu/<slug:slug>", DownloadEpubView.as_view(), name="stahnout-knihu"),
    ]

knihy/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.core.validators import FileExtensionValidator

"""
Po jakékoliv modifikaci kódu v tomto souboru je nutno provést migraci:
python manage.py makemigrations
python manage.py migrate
"""

class Author(models.Model):
    first_name = models.CharField(max_length=50, default="")
    last_name = models.CharField(max_length=50, null=True, blank=True)
    slug = models.SlugField(max_length=50, null=True, blank=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"
    
    def save(self, *args, **kwargs):
        self.slug = slugify(f"{self.first_name} {self.last_name}")
        super().save(*args, **kwargs)
    
    class Meta:
        ordering = ["last_name"]


class Genre(models.Model):
    genre = models.CharField(max_length=50)
    slug = models.SlugField(default="", null=False, db_index=True)
    icon = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.genre
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.genre)
        super().save(*args, **kwargs)
    
    class Meta:
        ordering = ["genre"]

class Publisher(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(default="", null=False, db_index=True)

    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

class Book(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    # genre = models.ForeignKey(Genre, on_delete=models.SET_NULL, null=True, blank=True)
    genre = models.ManyToManyField(Genre)
    publication_date = models.CharField(max_length=4)
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE, null=True, blank=True)
    ISBN = models.CharField(max_length=17, unique=True)
    summary = models.TextField()
    cover_image = models.ImageField(upload_to="book_covers/", null=True, blank=True)
    slug = models.SlugField(default="", null=False, db_index=True) # Harry Potter 1 => harry-potter-1
    hodnoceni = models.IntegerField(null=True, blank=True, default=0)
    epub_file = models.FileField(upload_to="epub_files/", null=True, blank=True, validators=[FileExtensionValidator(['epub', 'pdf'])], error_messages="Pouze formát EPUB nebo PDF.")
    
    def __str__(self):
        return self.title


    # def get_absolute_url(self):
    #     return reverse("detail-knihy", args=(str(self.id))) 
    def get_absolute_url(self):
        return reverse("detail-knihy", args=self.slug) 

    # po dodatečném doprogramování slugu je potřeba jeho hodnotu vytvořit a to zavoláním fce save
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

knihy/forms.py
from django import forms
from .models import Book, Author, Genre, Publisher
from django.core.exceptions import ValidationError



class PostBookForm(forms.ModelForm):
    # genre1 = forms.ModelChoiceField(queryset=Genre.objects.all(), empty_label="", widget=forms.Select(attrs={'class': 'form-control shadow-sm'}))
    # genre2 = forms.ModelChoiceField(queryset=Genre.objects.all(), required=False, empty_label="", widget=forms.Select(attrs={'class': 'form-control shadow-sm'}))
    # genre3 = forms.ModelChoiceField(queryset=Genre.objects.all(), required=False, empty_label="", widget=forms.Select(attrs={'class': 'form-control shadow-sm'}))
    
    
    author_search = forms.CharField(label='Autor', widget=forms.TextInput(attrs={"class": "form-control shadow-sm", "placeholder": "Zadej příjmení..."}))
    # epub_file = forms.ClearableFileInput(attrs={'class': 'form-control-file'})
    publisher_search = forms.CharField(label='Nakladatelství', widget=forms.TextInput(attrs={"class": "form-control shadow-sm", "placeholder": "Zadej název..."}))
    

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super().__init__(*args, **kwargs)

        # Check if the user is an admin
        if not (self.request and self.request.user.is_staff):
            # If not an admin, hide the epub_file field
            self.fields['epub_file'].widget = forms.HiddenInput()

    class Meta:
        model = Book
        fields = ("title", "author_search", "author", "genre", "publication_date", "publisher_search", "publisher", "ISBN", "summary", "cover_image", "epub_file")
    
    # přidávám class, se kterou pracuji v CSS; stejně tak můžu přidat jakýkoliv jiný parametr
        widgets = {
                'title': forms.TextInput(attrs={'class': 'form-control shadow-sm'}),
                'author': forms.HiddenInput(),
                # 'genre': forms.Select(attrs={'class': 'form-control shadow-sm'}),
                'genre': forms.CheckboxSelectMultiple(attrs={'class': 'list-unstyled'}),
                # 'genre': forms.SelectMultiple(),
                'publication_date': forms.DateInput(attrs={'class': 'form-control datepicker shadow-sm'}),
                'publisher': forms.HiddenInput(),
                'ISBN': forms.TextInput(attrs={'class': 'form-control shadow-sm'}),
                'summary': forms.Textarea(attrs={'class': 'form-control shadow-sm', 'rows': 4}),
                'cover_image': forms.ClearableFileInput(attrs={'class': 'form-control-file'}),
                'epub_file': forms.ClearableFileInput(attrs={'class': 'form-control-file'})
            }
        
        labels = {
            'title': 'Název',
            'genre': 'Žánr',
            'publication_date': 'Rok vydání',
            'publisher': 'Nakladatelství',
            'ISBN': 'ISBN',
            'summary': 'Souhrn',
            'cover_image': 'Obrázek obalu',
            'epub_file': 'E-kniha v EPUB formátu',
        }
    

class PostAuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ("first_name", "last_name")

    # přidávám class, se kterou pracuji v CSS; stejně tak můžu přidat jakýkoliv jiný parametr
        widgets = {
                'first_name': forms.TextInput(attrs={'class': 'form-control shadow-sm'}),
                'last_name': forms.TextInput(attrs={'class': 'form-control shadow-sm'}),
            }
        
        labels = {
            'first_name': 'Jméno',
            'last_name': 'Příjmení',
        }
    
    def clean_first_name(self):
        # Capitalize the first letter of the first name
        return self.cleaned_data['first_name'].capitalize()

    def clean_last_name(self):
        # Capitalize the first letter of the last name
        return self.cleaned_data['last_name'].capitalize()


class PostPublisherForm(forms.ModelForm):
    class Meta:
        model = Publisher
        fields = ("name",)

        widgets = {
                'name': forms.TextInput(attrs={'class': 'form-control shadow-sm'}),
             }
        labels = {
            "name": "Nakladatelství",
        }
    
    def clean_name(self):
        return self.cleaned_data["name"].capitalize()

knihy/templates/detail-autora.html
{% extends "base.html" %}
{% load static %}

{% block title %}
{{ author.first_name }} {{ author.last_name }}
{% endblock %}

{% block content %}


<h1>{{ author.first_name }} {{ author.last_name }}</h1>
<h2 style="margin-top: 20px;">Knihy</h2>
<div class="author-books">
    <ul class="author-books-list">
        {% for book in author.book_set.all %}
        <li class="ten-books">
            <a href="{% url 'detail-knihy' book.slug %}">
                {% if book.cover_image %}
                <img src="{{ book.cover_image.url }}" alt="{{ book.title }} Cover">
                {% else %}
                <img src="{% static 'images/empty_cover.webp' %}" style="border-radius: 15px 0 0 15px;" alt="Prázdný obal">
                {% endif %}
            </a>
            <p style="margin-top: 20px; width: 100%" class="prehled-knih fw-medium"> {{ book.title }} <br> ({{ book.publication_date }})</p>
        </li>
        {% empty %}
            <p>Žádné knihy nejsou dostupné.</p>
        {% endfor %}
    </ul>
</div>


{% endblock %}

knihy/templates/detail-knihy.html
{% extends "base.html" %}
{% load static %}

{% block title %}
{{    book.title }}
{% endblock %}

{% block content %}

<div class="name-book">
    <h1>{{ book.title }}</h1>
    <div class="upravit-smazat">
        {% if user.is_authenticated %}
            <a href="{% url 'upravit-knihu' book.slug %}">Upravit knihu</a>
        {% endif %}
        {% if user.is_staff %}
            <a href="{% url 'smazat-knihu' book.slug %}">Smazat knihu</a>
        {% endif %}
    </div>
</div>

<div class="kniha">
    <div class="obsah-knih">
        <div style="display: flex; flex-wrap: wrap;">
            {% if book.cover_image %}
            <img src="{{ book.cover_image.url }}" alt="{{ book.title }} Cover">
            {% else %}
            <img src="{% static 'images/empty_cover.webp' %}" style="border-radius: 15px 0 0 15px;" alt="Prázdný obal">
            {% endif %}
        
            <div class="info-knih">
                <div>
                    <p><strong>Napsal:</strong> <a class="fs-5" style="text-decoration: none;" href="{% url 'detail-autora' book.author.slug %}">{{ book.author }}</a></p>
                    <p><strong>Žánry:</strong>
                        {% for genre in book.genre.all %}
                            <a href="{% url 'zanr' genre.slug %}">{{ genre }}</a>{% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    </p>
                    <p><strong>Rok vydání:</strong> {{ book.publication_date }}</p>
                    <p><strong>Nakladatelství:</strong> 
                        {% if book.publisher %}
                        <a href="{% url 'detail-nakladatelstvi' book.publisher.slug %}">{{ book.publisher }}</a>
                        {% else %}
                        {{ book.publisher }}
                        {% endif %}
                    </p>
                    <p><strong>ISBN:</strong> {{book.ISBN }}</p>
                </div>
                {% if book.epub_file and user.is_staff%}
                <div style="width: 100%;">
                    <a href="{% url 'stahnout-knihu' book.slug %}"><button type="button" class="btn btn-primary">Stáhnout</button></a> 
                </div>
                {% endif %}
            </div>
        </div>

        <div class="hodnoceni">
            <div class="star-rating" data-rating="{{ book.hodnoceni}}">
                <script>
                    var rating = {{ book.hodnoceni }};
                    var starsContainer = document.querySelector('.star-rating');
                    var filledStars = Math.round((rating / 100) * 5);
        
                    for (var i = 0; i < filledStars; i++) {
                        var filledStar = document.createElement('span');
                        filledStar.className = 'star filled-star';
                        filledStar.innerHTML = '&#9733;';
                        starsContainer.appendChild(filledStar);
                    }
        
                    for (var i = filledStars; i < 5; i++) {
                        var emptyStar = document.createElement('span');
                        emptyStar.className = 'star';
                        emptyStar.innerHTML = '&#9734;';
                        starsContainer.appendChild(emptyStar);
                    }
                </script>
            </div>
            <p> {{ book.hodnoceni }} %</p>
        </div>
    </div>

    <div>
        <p><h5>Popis:</h5> {{ book.summary|safe }}</p>
    </div>
</div>

{% endblock %}

knihy/templates/detail-nakladatelstvi.html
{% extends "base.html" %}
{% load static %}

{% block title %}
{{ publisher.name }}
{% endblock %}

{% block content %}


<h1>{{ publisher.name }}</h1>
<h2 style="margin-top: 20px;">Knihy  ({{ publisher.book_set.count }})</h2>
<div class="author-books">
    <ul class="author-books-list">
        {% for book in publisher.book_set.all %}
        <li class="ten-books">
            <a href="{% url 'detail-knihy' book.slug %}">
                {% if book.cover_image %}
                <img src="{{ book.cover_image.url }}" alt="{{ book.title }} Cover">
                {% else %}
                <img src="{% static 'images/empty_cover.webp' %}" style="border-radius: 15px 0 0 15px;" alt="Prázdný obal">
                {% endif %}
            </a>
            <p style="margin-top: 20px; width: 100%" class="prehled-knih fw-medium"> {{ book.title }} <br> ({{ book.publication_date }})</p>
        </li>
        {% empty %}
            <p>Žádné knihy nejsou dostupné.</p>
        {% endfor %}
    </ul>
</div>


{% endblock %}

knihy/templates/knihy.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Přehled knih
{% endblock %}

{% block content %}



<div id="carouselExampleAutoplaying" class="carousel carousel-dark slide" data-bs-ride="carousel">
    <div class="carousel-indicators" style="margin-bottom: 0;">
        <button type="button" data-bs-slide-to="0" class="active dot" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-slide-to="1" class="dot" aria-label="Slide 2"></button>
        <button type="button" data-bs-slide-to="2" class="dot" aria-label="Slide 3"></button>
        <button type="button" data-bs-slide-to="3" class="dot" aria-label="Slide 4"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="../../static/images/slide1.png" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="../../static/images/slide2.png" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="../../static/images/slide3.png" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="../../static/images/slide4.png" class="d-block w-100" alt="...">
        </div>
    </div>
    <button style="width: 4%;" class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
        <span style="height: 100%; background-color: #000000;width: 4rem;" class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button style="width: 4%;" class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
        <span style="height: 100%; background-color: #000000;width: 4rem;" class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>



<div class="books">
    <h1>Přehled nových knih</h1>
    <div class="new-books police">
        <ul style="justify-content: space-around;">
            {% for book in object_list %}
            <li class="ten-books">
                <a href="{% url 'detail-knihy' book.slug %}">
                    {% if book.cover_image %}
                    <img src="{{ book.cover_image.url }}" alt="{{ book.title }} Cover">
                    {% else %}
                    <img src="{% static 'images/empty_cover.webp' %}" style="border-radius: 15px 0 0 15px;" alt="Prázdný obal">
                    {% endif %}
                </a>
                <p style="width:100%" class="prehled-knih fw-medium"> {{ book.author }} <br> {{ book.title }}</p>
            </li>
            {% endfor %}
        </ul>
    </div>
    <a href="{% url 'vsechny-knihy' %}"><button type="button" class="btn btn-primary shadow-sm">Více knih</button></a>
</div>

<div class="autori">
    <div class="authors">
        <h1>Přehled autorů</h1>
        <div class="new-author">
            <ul>
            {% for author in authors %}
                <li class="ten-authors">
                    <a href="{% url 'detail-autora' author.slug %}" style="margin-bottom: 0; cursor: pointer" class="prehled-knih fs-5 fw-medium">{{ author.first_name }} {{ author.last_name }}
                    </a>
                </li>
                {% endfor %}
            </ul>
        </div>
        <a href="{% url 'vsichni-autori' %}"><button type="button" class="btn btn-primary shadow-sm">Více autorů</button></a>
    </div>
    <div class="pridat-btn">
        <div class="add-img">
            <img src="../../static/images/book.webp">
            <a href="{% url 'pridat-knihu' %}"><button type="button" class="btn btn-primary shadow-sm">Přidat knihu</button></a>
        </div>
        <div class="add-img">
            <img src="../../static/images/author.webp">
            <a href="{% url 'pridat-autora' %}"><button type="button" class="btn btn-primary">Přidat autora</button></a>
        </div>
    </div>
</div>

<div class="genre">
    <h1>Seznam žánrů</h1>
    <div style="margin-top: 30px; width: 100%;">
        <ul>
            {% for genre in genres %}
            <li>
                <a href="{% url 'zanr' genre.slug %}"><i class="{{ genre.icon }}"></i> {{ genre }} ({{ genre.book_set.count }})</a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>

{% endblock%}

knihy/templates/pridat-autora.html
{% extends "base.html" %}

{% block title %}
Přidat autora
{% endblock %}

{% block content %}

<h1>Přidat autora</h1>
<div class="form-group">
    <form method="post" action="{% url 'pridat-autora' %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        {% if error_message %}
            <p>{{ error_message }}</p>
        {% endif %}
        <button type="submit" class="btn btn-primary">Přidat</button>
    </form>
    
</div>


{% endblock %}

knihy/templates/pridat-knihu.html
{% extends "base.html" %}

{% block title %}
    Přidat knihu
{% endblock %}

{% block content %}
    <h1>Přidání nové knihy</h1>

    <div class="form-group">
        <form method="post" action="{% url 'pridat-knihu' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}

            <!-- Include jQuery and jQuery UI stylesheets -->
            <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
            <!-- Include jQuery library -->
            <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
            <!-- Include jQuery UI library -->
            <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
            
            <script>
                $( function() {
                    $( "#id_author_search" ).autocomplete({
                        minLength: 1,
                        source: function(request, response) {
                            $.ajax({
                                url: "{% url 'author-autocomplete' %}",
                                dataType: "json",
                                data: {
                                    q: request.term
                                },
                                success: function(data) {
                                    response(data);
                                }
                            });
                        },
                        select: function (event, ui) {
                            // Set the displayed text to the author's last name
                            $("#id_author").val(ui.item.id);
                            
                            // Set the actual value to the author's ID
                            $("#id_author_search").val(ui.item.label);
        
                            return false; // Prevent the default behavior
                        }
                    });
                } );
                $( function() {
                    $( "#id_publisher_search" ).autocomplete({
                        minLength: 1,
                        source: function(request, response) {
                            $.ajax({
                                url: "{% url 'publisher-autocomplete' %}",
                                dataType: "json",
                                data: {
                                    q: request.term
                                },
                                success: function(data) {
                                    response(data);
                                }
                            });
                        },
                        select: function (event, ui) {
                            // Set the displayed text to the author's last name
                            $("#id_publisher").val(ui.item.id);
                            
                            // Set the actual value to the author's ID
                            $("#id_publisher_search").val(ui.item.label);
        
                            return false; // Prevent the default behavior
                        }
                    });
                } );
            </script>

            <button type="submit" class="btn btn-primary">Přidat</button>
        </form>
    </div>

{% endblock content %}

knihy/templates/pridat-nakladatelstvi.html
{% extends "base.html" %}

{% block title %}
Přidat nakladatelství
{% endblock %}

{% block content %}

<h1>Přidat nakladatelství</h1>
<div class="form-group">
    <form method="post" action="{% url 'pridat-nakladatelstvi' %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        {% if error_message %}
            <p>{{ error_message }}</p>
        {% endif %}
        <button type="submit" class="btn btn-primary">Přidat</button>
    </form>
    
</div>


{% endblock %}

knihy/templates/smazat-knihu.html
{% extends 'base.html' %}

{% block title %}
    Smazat knihu {{ book.title }}
{% endblock %}

{% block content %}

{% if user.is_staff %}
<h1 style="">Smazat knihu {{ book.title }}</h1>

<div class="form-group">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <strong>Opravdu chceš knihu smazat?</strong>
        <br>
        <button type="submit" class="btn btn-primary">Smazat</button>
    </form>
</div>
{% else %}
<h1>Přístup odepřen.</h1>
{% endif %}

{% endblock %}

knihy/templates/upravit-knihu.html
{% extends "base.html" %}

{% block title %}
    Upravit knihu {{ book.title }}
{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<h1 style="">Upravit knihu {{ book.title }}</h1>

<div class="form-group">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}

        <!-- Include jQuery and jQuery UI stylesheets -->
        <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
        <!-- Include jQuery library -->
        <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
        <!-- Include jQuery UI library -->
        <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>

        <script>
            $( function() {
                $( "#id_author_search" ).autocomplete({
                    minLength: 2,
                    source: function(request, response) {
                        $.ajax({
                            url: "{% url 'author-autocomplete' %}",
                            dataType: "json",
                            data: {
                                q: request.term
                            },
                            success: function(data) {
                                response(data);
                            }
                        });
                    },
                    select: function (event, ui) {
                        // Set the displayed text to the author's last name
                        $("#id_author").val(ui.item.id);
                        
                        // Set the actual value to the author's ID
                        $("#id_author_search").val(ui.item.label);
    
                        return false; // Prevent the default behavior
                    }
                });
            } );
            $( function() {
                $( "#id_publisher_search" ).autocomplete({
                    minLength: 1,
                    source: function(request, response) {
                        $.ajax({
                            url: "{% url 'publisher-autocomplete' %}",
                            dataType: "json",
                            data: {
                                q: request.term
                            },
                            success: function(data) {
                                response(data);
                            }
                        });
                    },
                    select: function (event, ui) {
                        // Set the displayed text to the author's last name
                        $("#id_publisher").val(ui.item.id);
                        
                        // Set the actual value to the author's ID
                        $("#id_publisher_search").val(ui.item.label);
    
                        return false; // Prevent the default behavior
                    }
                });
            } );
        </script>

        <button type="submit" class="btn btn-primary">Uložit</button>
    </form>
</div>
{% else %}
<h1>Přístup odepřen.</h1>
{% endif %}

{% endblock %}

knihy/templates/vsechny-knihy-abecedne.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Seznam všech knih
{% endblock %}


{% block content %}
<h1>Abecední přehled všech knih - písmeno {{ selected_char }}</h1>

<div class="abeceda-autoru">
    <ul>
        <li>
            <a href="{% url 'vsechny-knihy' %}">#</a>
        </li>
        {% for char in 'ABCČDEFGHIJKLMNOPQRŘSŠTUVWXYZŽ'%}
        <li>
            <a href="{% url 'vsechny-knihy-abecedne' char %}" class="{% if selected_char == char %}active{% endif %}">{{ char }}</a>
        </li>
        {% endfor %} 
    </ul>  
     
</div>    

<div class="all-books police2">
    <ul>
        {% for book in filtered_books %}
        <li class="ten-books">
            <a href="{% url 'detail-knihy' book.slug %}">
                {% if book.cover_image %}
                <img src="{{ book.cover_image.url }}" alt="{{ book.title }} Cover">
                {% else %}
                <img src="{% static 'images/empty_cover.webp' %}" style="border-radius: 15px 0 0 15px; height: 135px;" alt="Prázdný obal">
                {% endif %}
            </a>
            <p style="font-size: 15px; width:100%" class="prehled-knih fw-medium"> {{ book.title }} <br> {{ book.author }}  </p>
        </li>
        {% endfor %}
    </ul>
</div>
{% if all_books.paginator.num_pages > 1%}
    <div class="pagination">
        <span class="step-links">
            {% if all_books.has_previous %}
                <a href="?page=1">&laquo; první</a>
                <a href="?page={{ all_books.previous_page_number }}">předešlá</a>
            {% endif %}

            <span class="current">
                Stránka {{ all_books.number }} z {{ all_books.paginator.num_pages }}
            </span>

            {% if all_books.has_next %}
                <a href="?page={{ all_books.next_page_number }}">další</a>
                <a href="?page={{ all_books.paginator.num_pages }}">poslední &raquo;</a>
            {% endif %}
        </span>
    </div>
{% endif %}


{% endblock %}